remote_theme: thelehhman/plainwhite-jekyll

plainwhite:
  name: Shaoor Munir
  tagline: Developer
  date_format: "%b %-d, %Y"
  disqus_shortname: shaoorgithubpage
  sitemap: true
  show_excerpts: true
  dark_mode: true
  search: true


  social_links:
    twitter: Shaoor_Munir
    github: shaoormunir
    linkedIn: pk/shaoormunir